# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-01 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='result',
            field=models.CharField(blank=True, choices=[('1-0', '1-0'), ('i-o', 'i-o'), ('+:-', '+:-'), ('0-1', '0-1'), ('o-i', 'o-i'), ('-:+', '-:+'), ('o-o', 'o-o'), ('-:-', '-:-'), ('1/2-1/2', '1/2-1/2'), ('i/2-i/2', 'i/2-i/2')], help_text='Game status/result.', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='reliability',
            field=models.IntegerField(default=2, help_text='Reliability rating.'),
        ),
    ]
